# Generated by Django 3.2.23 on 2023-12-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='orign',
            new_name='origin',
        ),
    ]
